spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=TRUE
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'

billing:
  periods:
    free-start-time: '07:00'
    free-end-time: '12:00'

server:
  port: 8080
